source 'https://rubygems.org'

gem 'utter' ,  :path => "./../"
gem 'rack'
gem 'minitest'
gem 'thin'
#gem 'puma'
gem 'shotgun'
gem 'redis'
gem 'rake'
#gem 'rack-test'
#gem "rack-minitest", git: "git://github.com/brandonweiss/rack-minitest.git"

#'TODO place your private gem server here' if not given then local machine
=begin
source 'https://gems.example.com' do
  # loading project_name API v1 
  gem 'project_name\users'   ,  '~>1'
  gem 'project_name\statues' ,  '~>1'

  # loading project_name API v2
  gem 'project_name\users'   ,  '~>2'
  gem 'project_name\statues' ,  '~>2'
end
=end
